@url=http://localhost:9002
@chaistandId=5f1cbf0a841bd95994c3d692

###
### Get all chaistands
GET {{url}}/api

###
### Get chaistand by id
GET {{url}}/api/{{chaistandId}}

###
### Get all mixins
GET {{url}}/api/mixins

###
### Create order
POST {{url}}/api/{{chaistandId}}/orders
Content-Type: application/json

{
    "name": "Mohammed",
    "cups": 1,
    "mixins": [
        {
            "_id":"5f1cb8f7c6b8ba5e59efc8a3",
            "name":"Milk",
            "amount":"1"
        },
        {
            "_id":"5f1cb905c6b8ba5e59efc8a4",
            "name":"Sugar",
            "amount":"1"
        }
    ]
}

###
### Get all orders
GET {{url}}/api/{{chaistandId}}/orders

###
### Get order by name
GET {{url}}/api/{{chaistandId}}/orders/Sakina%20wifey

###
### Update order by ID
PATCH {{url}}/api/{{chaistandId}}/orders/5f1cc4be16f9555e0033ac5c
Content-Type: application/json

{
    "name": "Sakina wifey",
    "cups": 2,
    "mixins": [
        {
            "_id":"5f1cb8f7c6b8ba5e59efc8a3",
            "name":"Milk",
            "amount":"2"
        },
        {
            "_id":"5f1cb905c6b8ba5e59efc8a4",
            "name":"Sugar",
            "amount":"3"
        }
    ]
}